import type { Metadata } from "next";
import Header from "../../components/Header";
import Footer from "../../components/Footer"; 
export const metadata: Metadata = {
  title: "Survivors",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
