import type { Metadata } from "next";
import Header from "../../boilerPlate/Header";
import Footer from "../../boilerPlate/Footer"; 
import ThemeRegistry from '@/ThemeRegistry';
import './globals.css'
export const metadata: Metadata = {
  title: "Survivors",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
         
          <Header />
          
          <main>
              {children}
          </main>

          <Footer />
        </ThemeRegistry>
      </body>
    </html>
  );
}
